#index:
#    path: /
#    controller: App\Controller\DefaultController::index

hello:
    path : /hello/
    controller: App\Controller\HelloController::HelloAction

bookGET:
    path: /book
    methods: GET
    controller: App\Controller\BookController::getBook

bookPOST:
    path: /book
    methods: POST
    controller: App\Controller\BookController::postBook

bookPATCH:
    path: /book
    methods: PATCH
    controller: App\Controller\BookController::patchBook